//! Observation types representing individual memory entries.
//!
//! An [`Observation`] is the atomic unit of memory in rusty-brain. Each
//! observation captures what an agent noticed during a coding session and is
//! classified by an [`ObservationType`]. Optional [`ObservationMetadata`]
//! carries extensible context (files, platform, custom key-value pairs).

use crate::error::{RustyBrainError, error_codes};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use ulid::Ulid;

/// Classification tag for an [`Observation`].
///
/// Serialized as lowercase strings (e.g. `"discovery"`, `"bugfix"`).
/// The enum is `#[non_exhaustive]` to allow new variants in future releases.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ObservationType {
    /// A new insight or finding encountered during a session.
    Discovery,
    /// An architectural or design decision made by the agent.
    Decision,
    /// A problem or issue identified in the codebase.
    Problem,
    /// A resolution or fix applied to a known problem.
    Solution,
    /// A recurring pattern observed across sessions or files.
    Pattern,
    /// A potential risk or caveat worth remembering.
    Warning,
    /// A positive outcome or milestone achieved.
    Success,
    /// A code refactoring operation.
    Refactor,
    /// A bug fix applied to the codebase.
    Bugfix,
    /// A new feature implemented.
    Feature,
}

impl std::fmt::Display for ObservationType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            Self::Discovery => "discovery",
            Self::Decision => "decision",
            Self::Problem => "problem",
            Self::Solution => "solution",
            Self::Pattern => "pattern",
            Self::Warning => "warning",
            Self::Success => "success",
            Self::Refactor => "refactor",
            Self::Bugfix => "bugfix",
            Self::Feature => "feature",
        };
        f.write_str(s)
    }
}

impl std::str::FromStr for ObservationType {
    type Err = RustyBrainError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "discovery" => Ok(Self::Discovery),
            "decision" => Ok(Self::Decision),
            "problem" => Ok(Self::Problem),
            "solution" => Ok(Self::Solution),
            "pattern" => Ok(Self::Pattern),
            "warning" => Ok(Self::Warning),
            "success" => Ok(Self::Success),
            "refactor" => Ok(Self::Refactor),
            "bugfix" => Ok(Self::Bugfix),
            "feature" => Ok(Self::Feature),
            _ => Err(RustyBrainError::InvalidInput {
                code: error_codes::E_INPUT_INVALID_FORMAT,
                message: format!("unknown ObservationType: {s}"),
            }),
        }
    }
}

/// A single memory entry recorded by an agent during a coding session.
///
/// Observations are immutable once created. The `id` and `timestamp` are
/// auto-generated by [`Observation::new`]. Serialized with camelCase keys;
/// `obs_type` is serialized as `"type"` and `tool_name` as `"toolName"`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Observation {
    /// Unique identifier (ULID), auto-generated on construction.
    /// Lexicographically sortable by creation time.
    pub id: Ulid,
    /// UTC timestamp of when the observation was recorded.
    pub timestamp: DateTime<Utc>,
    /// Classification of this observation. Serialized as `"type"`.
    #[serde(rename = "type")]
    pub obs_type: ObservationType,
    /// Name of the tool that produced this observation. Serialized as `"toolName"`.
    #[serde(rename = "toolName")]
    pub tool_name: String,
    /// Short human-readable summary (must not be empty).
    pub summary: String,
    /// Detailed content body. Optional per EC-4.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Optional extensible metadata. Omitted from JSON when `None`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ObservationMetadata>,
}

impl Observation {
    /// Creates a new `Observation`, auto-generating id and timestamp.
    ///
    /// # Errors
    ///
    /// Returns [`RustyBrainError::InvalidInput`] with code
    /// [`error_codes::E_INPUT_EMPTY_FIELD`] if `summary` or `tool_name` is empty
    /// or contains only whitespace. Content is optional per EC-4.
    pub fn new(
        obs_type: ObservationType,
        tool_name: String,
        summary: String,
        content: Option<String>,
        metadata: Option<ObservationMetadata>,
    ) -> Result<Self, RustyBrainError> {
        if tool_name.trim().is_empty() {
            return Err(RustyBrainError::InvalidInput {
                code: error_codes::E_INPUT_EMPTY_FIELD,
                message: "tool_name must not be empty or whitespace-only".to_string(),
            });
        }
        if summary.trim().is_empty() {
            return Err(RustyBrainError::InvalidInput {
                code: error_codes::E_INPUT_EMPTY_FIELD,
                message: "summary must not be empty or whitespace-only".to_string(),
            });
        }
        // Normalize empty/whitespace content to None
        let content = content.filter(|c| !c.trim().is_empty());
        Ok(Self {
            id: Ulid::new(),
            timestamp: Utc::now(),
            obs_type,
            tool_name,
            summary,
            content,
            metadata,
        })
    }
}

/// Extensible metadata attached to an [`Observation`].
///
/// All fields default to their zero/empty values via `#[serde(default)]`.
/// The `extra` map is flattened into the parent JSON object, allowing
/// arbitrary key-value pairs alongside the named fields.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ObservationMetadata {
    /// File paths relevant to this observation.
    #[serde(default)]
    pub files: Vec<String>,
    /// Platform identifier (e.g. `"darwin"`, `"linux"`).
    #[serde(default)]
    pub platform: String,
    /// Project key used to scope observations across repositories.
    #[serde(default)]
    pub project_key: String,
    /// Whether the content was compressed before storage.
    #[serde(default)]
    pub compressed: bool,
    /// Optional session identifier linking this observation to a session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// Arbitrary additional key-value pairs, flattened into the JSON object.
    ///
    /// **Important**: Do not insert keys that collide with the camelCase names of
    /// named fields (`"files"`, `"platform"`, `"projectKey"`, `"compressed"`,
    /// `"sessionId"`). Doing so produces duplicate JSON keys with undefined
    /// round-trip behavior.
    #[serde(flatten)]
    pub extra: HashMap<String, serde_json::Value>,
}

#[cfg(test)]
#[path = "observation_tests.rs"]
mod tests;
